name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, check and build app
        run: |
          npm install
          npm run build
      - name: Update matching Github page
        run: |
          git clone https://github.com/dagoma3d/dagoma3d.github.io.git
          cp -r ./build/* ./dagoma3d.github.io/
          cd dagoma3d.github.io
          git status
